<?php

use Illuminate\Database\Seeder;

class ProgrammeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('Programmes')->insert([
            [
                'center_faculty_id' => '5',
                'category' => '1',
                'level' => '1',
                'programme_name' => 'Cambridge GCE A Level Arts',
            ],
            [
                'center_faculty_id' => '5',
                'category' => '1',
                'level' => '1',
                'programme_name' => 'Cambridge GCE A Level Science',
            ],
            [
                'center_faculty_id' => '5',
                'category' => '1',
                'level' => '2',
                'programme_name' => 'Foundation in Arts',
            ],
            [
                'center_faculty_id' => '5',
                'category' => '1',
                'level' => '2',
                'programme_name' => 'Foundation in Science',
            ],
            [
                'center_faculty_id' => '5',
                'category' => '1',
                'level' => '2',
                'programme_name' => 'Foundation in Accounting',
            ],
            [
                'center_faculty_id' => '5',
                'category' => '1',
                'level' => '2',
                'programme_name' => 'Foundation in Business',
            ],
            [
                'center_faculty_id' => '5',
                'category' => '1',
                'level' => '2',
                'programme_name' => 'Foundation in Engineering',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Accounting)',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Mass Communication (Advertising)',

            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Architecture',

            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma In Aquaculture',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Baking and Cake Artistry',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Banking and Finance)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Banking and Finance',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Mass Communication (Broadcast Communication)',
            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Technology (Building)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Business Administration)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Business Economics)',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Science (Business Information Systems)',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Science (Chemistry and Biology)',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Communication and Media Studies',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Science (Computer Science and Computer Mathematics)',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Science (Computer Science and Management Mathematics)',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Social Science (Counselling)',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Culinary Arts',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Computer Science (Data Science)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (E-Commerce and Marketing)',
            ],
            [
                'center_faculty_id' => '22',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Technology (Electronic Engineering)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Entrepreneurship',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Event Management',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Finance and Investment)',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Food Science',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Graphic Design',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Hospitality Management (Hotel Management)',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Hotel Management',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Human Resource Management)',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Science (Information Systems Engineering)',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Information Systems (ICT Applications)',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Interactive Software Technology',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (International Business)',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Science (Internet Technology)',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Information Technology (ICT Systems Support)',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Information Technology (Mobile Application Development)',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Mass Communication (Journalism)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Logistics and Supply Chain Management)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Marketing)',
            ],
            [
                'center_faculty_id' => '22',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Technology (Mechanical and Manufacturing Engineering)',
            ],
            [
                'center_faculty_id' => '22',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Technology (Mechatronics)',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Mass Communication (Media Studies)',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Science (Microelectronics with Computer Communications)',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma In Multimedia Design',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Mass Communication (Public Relations)',
            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Real Estate Management',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Business Studies (Retail Management)',
            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Quantity Surveying',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Software Engineering',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Sport and Exercise Science',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '3',
                'programme_name' => 'Diploma in Hospitality Management (Tourism)',
            ],
            // Diploma Programme List End
            // Degree Programme List Start
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Accounting (Honours)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Business (Honours) Accounting and Finance',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Communication (Honours) in Advertising',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Science (Hons) in Analytical Chemistry',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Science (Hons) in Applied Physics (Instrumentation)',
            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Science in Architecture (Honours)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Banking and Finance (Honours)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Business Administration (Honours)',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Science (Hons) in Bioscience with Chemistry',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Communication (Honours) in Broadcasting',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Commerce (Honours)',
            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Construction Management and Economics (Honours)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Corporate Administration (Honours)',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Creative Multimedia (Honours)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Business (Honours) in Entrepreneurship',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Economics (Honours)',
            ],
            [
                'center_faculty_id' => '22',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Engineering (Honours) Electrical and Electronics',
            ],
            [
                'center_faculty_id' => '22',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Engineering (Honours) Electronic (Communication)',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Arts (Honours) English with Drama',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Information Systems (Honours) in Enterprise Information Systems',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor in Tourism Management (Honours) (Event Management)',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Design (Honours) in Fashion Design',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Finance (Honours)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Finance and Investment (Honours)',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Science (Hons) in Food Science',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Design (Honours) in Graphic Design',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Hospitality and Catering Management',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor Of Hospitality Management',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Business (Honours) in Human Resource Management',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Information Technology (Honours) in Information Security',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Computer Science (Honours) in Interactive Software Technology',
            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Interior Architecture (Honours)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Business (Honours) in International Business',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Business (Honours) International Business Management',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Information Technology (Honours) in Internet Technology',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Communication (Honours) in Journalism',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Business (Honours) in Logistics and Supply Chain Management',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Business (Honours) in Marketing',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Science (Honours) in Microelectronics (Embedded Technology)',
            ],
            [
                'center_faculty_id' => '22',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Engineering (Honours) Mechanical',
            ],
            [
                'center_faculty_id' => '22',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Engineering (Honours) Mechatronic',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Science (Honours) in Management Mathematics with Computing',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Communication (Honours) in Media Studies',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Social Science (Honours) in Psychology',
            ],
            [
                'center_faculty_id' => '20',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Public Relations (Honours)',
            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Quantity Surveying (Honours)',
            ],
            [
                'center_faculty_id' => '19',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Real Estate Management(Honours)',
            ],
            [
                'center_faculty_id' => '17',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Retail Management (Honours)',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Science (Hons) in Sports and Exercise Science',
            ],
            [
                'center_faculty_id' => '18',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Computer Science (Honours) in Software Engineering',
            ],
            [
                'center_faculty_id' => '21',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Information Technology (Honours) in Software Systems Development',
            ],
            [
                'center_faculty_id' => '23',
                'category' => '2',
                'level' => '4',
                'programme_name' => 'Bachelor of Tourism Management (Honours)',
            ],
            // Degree Programme List End
            // Master Programme Start
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '4',
                'programme_name' => 'Master of Accounting and Finance [KPT/JPS(N344/7/0523)08/23]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Arts (Psychology) [KPT/JPS(N/322/7/0207)07/25]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Business Administration [KPT/JPS(N/340/7/0643)22/20]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Computer Science [KPT/JPS(N/482/7/0804)08/23]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Corporate Governance [KPT/JPS(N345/7/2064)02/23]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Engineering Science [KPT/JPS(N/520/7/0222)04/25]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Investment Management [KPT/JPS(N/343/7/0238)22/22]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Science [KPT/JPS(N/440/7/0027)04/22]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Science (Life Science) [KPT/JPS(N/420/7/0006)05/22]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '5',
                'programme_name' => 'Master of Science (Food Science) [KPT/JPS(N/542/7/0036)22/25]',
            ],
            // Master Programme Start End
            // Doctoria Programme List Start
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '6',
                'programme_name' => 'Doctor of Philosophy (Computer Science) [KPT/JPS(N/482/8/0788)20/25]',
            ],
            [
                'center_faculty_id' => '4',
                'category' => '3',
                'level' => '6',
                'programme_name' => 'Doctor of Philosophy (Life Sciences) [KPT/JPS(N/420/8/0025)20/25',
            ]
        ]);
    }
}
